### ISSUE TITLE
Build failure on 6.15.6

### ISSUE THREAD

**Issue by adavidzh** [amd/amd_energy#17]
Hi,

I was using `dkms` but it was quite terse:
```console
$ dkms build amd_energy/1.0
Deprecated feature: CLEAN (/var/lib/dkms/amd_energy/1.0/source/dkms.conf)
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/amd_energy/1.0/source/dkms.conf)
Sign command: /lib/modules/6.15.6-1.el9.elrepo.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
make -j64 KERNELRELEASE=6.15.6-1.el9.elrepo.x86_64 default KVER=6.15.6-1.el9.elrepo.x86_64

Error! Bad return status for module build on kernel: 6.15.6-1.el9.elrepo.x86_64 (x86_64)
Consult /var/lib/dkms/amd_energy/1.0/build/make.log for more information.
```

The contents of `/var/lib/dkms/amd_energy/1.0/build/make.log` are
```console
$ cat /var/lib/dkms/amd_energy/1.0/build/make.log
DKMS (dkms-3.2.1) make.log for amd_energy/1.0 for kernel 6.15.6-1.el9.elrepo.x86_64 (x86_64)
Wed Jul 30 06:55:14 PM CEST 2025

Building module(s)
# command: make -j64 KERNELRELEASE=6.15.6-1.el9.elrepo.x86_64 default KVER=6.15.6-1.el9.elrepo.x86_64
export CONFIG_SENSOR_AMD_ENERGY=m;	\
make -C /lib/modules/`uname -r`/build M=$PWD modules
make[1]: Entering directory '/usr/src/kernels/6.15.6-1.el9.elrepo.x86_64'
make[2]: Entering directory '/var/lib/dkms/amd_energy/1.0/build'
  CC [M]  amd_energy.o
amd_energy.c:366:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  366 |         .remove = amd_energy_remove,
      |                   ^~~~~~~~~~~~~~~~~
amd_energy.c:366:19: note: (near initialization for ‘amd_energy_driver.remove’)
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/kernels/6.15.6-1.el9.elrepo.x86_64/scripts/Makefile.build:203: amd_energy.o] Error 1
make[3]: *** [/usr/src/kernels/6.15.6-1.el9.elrepo.x86_64/Makefile:2003: .] Error 2
make[2]: *** [/usr/src/kernels/6.15.6-1.el9.elrepo.x86_64/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/amd_energy/1.0/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.15.6-1.el9.elrepo.x86_64'
make: *** [Makefile:15: default] Error 2

# exit code: 2
# elapsed time: 00:00:00
----------------------------------------------------------------
```

I tried also from the source and got the same warning-cum-error (as expected).

I found a reference to this sort of `-Werror=incompatible-pointer-types` issues in https://github.com/xmm7360/xmm7360-pci/pull/220 in case that can help inspire a solution.

Meanwhile, any way to disable `-Werror=incompatible-pointer-types`?

**Comment by ryant00000** [comment]
I believe the issue I ran into today is related. I modified the relevant function as follows, which seems to have worked correctly:
```
static void amd_energy_remove(struct platform_device *pdev)
{
        struct amd_energy_data *data = dev_get_drvdata(&pdev->dev);

        if (data && data->wrap_accumulate)
                kthread_stop(data->wrap_accumulate);

}

```
As a definite _not an expert_ on this, I asked an llm which told me:
```
the Linux kernel changed this signature to return void for consistency and to simplify error handling in drivers.
```
I'm not sure if this is the correct solution, but it does seem to be a solution. For completeness's sake, I am on 6.15.4.
